---
- name: Install Tomcat on Tomcat Server
  hosts: tomcat
  become: yes

  tasks:

    - name: Install Tomcat
      apt:
        name: tomcat10
        state: present
        update_cache: yes

    - name: Start Tomcat
      systemd:
        name: tomcat10
        state: started
        enabled: yes
